# Generated by Django 4.1.7 on 2023-03-21 09:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserFANotifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField(unique=True)),
                ('cookie_a', models.CharField(max_length=255)),
                ('cookie_b', models.CharField(max_length=255)),
                ('update_interval', models.DurationField(default=datetime.timedelta(seconds=3600))),
                ('previous_notifications', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
